# GPIO 1 = TX
# GPIO 3 = RX
# GPIO 2 = inverted LED
# GPIO 4 = mechanical Button

esphome:
  name: xy-wfpow
  friendly_name: XY-WFPOW

esp8266:
  board: esp8285

# Enable logging
logger:
  baud_rate: 0

#       falls kein MQTT Broker verwendet wird auskommentiert lassen.
#  ! Warning     !!!!!!!!!!!!!!!!
#    If you enable MQTT and you do not use the “native API” for Home Assistant,
#    you must remove the api: line from your ESPHome configuration, otherwise the ESP will
#    reboot every 15 minutes because no client connected to the native API.
#mqtt:
#  broker: !secret mqtt_IP
#  port: 8883
#  username: !secret mqtt_user
#  password: !secret mqtt_password

# Enable Home Assistant API
api:
  encryption:
    key: !secret apixywfpow

ota:
  password: !secret otaxywfpow

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xy-Wfpow Fallback Hotspot"
    password: "cNrHDxhh7P6t"

uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600

captive_portal:

binary_sensor:
  - platform: gpio
    name: "GPIO4 Taste"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
      
switch:
  - platform: gpio
    pin: GPIO2
    inverted: true
    name: "GPIO2 LED inverted"
