esphome:
  name: xy-wfpow
  friendly_name: XY-WFPOW

esp8266:
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret apixywfpow

ota:
  password: !secret otaxywfpow

web_server:
  port: 9005

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: !secret xywfpow_IP
    gateway: !secret gateway
    subnet: !secret subnet

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xy-Wfpow Fallback Hotspot"
    password: "cNrHDxhh7P6t"

captive_portal:

binary_sensor:
  - platform: gpio
    pin: GPIO1
    name: "GPIO1 TX"
  
  - platform: gpio
    pin: GPIO3
    name: "GPIO3 RX"
  
  - platform: gpio
    name: "GPIO4 Taste"
    pin:
      number: GPIO4
      mode: INPUT_PULLUP
      inverted: True
    
    
switch:
  - platform: gpio
    pin: GPIO2
    inverted: true
    name: "GPIO2 LED inverted"
  
